"""Secondary Capture Fuzzer - DICOM SC Image Mutations.

Category: structural

Targets Secondary Capture (SC) DICOM objects by corrupting pixel geometry,
color space declarations, frame count mismatches, and bit depth violations.
SC images are generated by virtually every imaging device and workstation
as screenshots, derived images, and report overlays.

Attack surface rationale:
  SC parsers trust SamplesPerPixel and PhotometricInterpretation to select
  a color decoder, and trust NumberOfFrames * Rows * Columns * (Bits/8) to
  allocate a pixel buffer. When these fields are inconsistent or overflow,
  parsers that skip validation are vulnerable to heap-buffer overflows,
  channel-count mismatches, and divide-by-zero in display pipeline.

Dataset-level attacks:
- color_space_mismatch: PhotometricInterpretation=RGB with SamplesPerPixel=1
- ycbcr_no_compression: YBR_FULL_422 declared but Transfer Syntax is uncompressed
- frame_count_overflow: NumberOfFrames >> PixelData (OOB in multi-frame SC)
- multiframe_no_timing: NumberOfFrames=10 with no FrameTime or FrameTimeVector
- bits_allocated_64: BitsAllocated=64 (non-standard, parser dispatch confusion)
- bits_allocated_1_size_mismatch: BitsAllocated=1 with byte-aligned pixel data
- no_pixel_data: SC SOPClassUID + large dimensions but no PixelData
- empty_pixel_data: PixelData present but zero bytes
- rgba_four_samples: SamplesPerPixel=4 with RGB photometric (RGBA not in DICOM standard)
- rows_zero: Rows=0 / Columns=0 (divide-by-zero in dimension-based allocation)
- conversion_type_missing: multi-frame SC without required ConversionType
- palette_color_missing_lut: PALETTE COLOR without LUT Data attributes
"""

from __future__ import annotations

import random

from pydicom.dataset import Dataset

from dicom_fuzzer.utils.logger import get_logger

from .base import FormatFuzzerBase

logger = get_logger(__name__)

# Secondary Capture SOP Class UIDs
_SC_SOP_CLASSES = frozenset(
    {
        "1.2.840.10008.5.1.4.1.1.7",  # Secondary Capture Image Storage
        "1.2.840.10008.5.1.4.1.1.7.1",  # Multi-frame Single Bit SC
        "1.2.840.10008.5.1.4.1.1.7.2",  # Multi-frame Grayscale Byte SC
        "1.2.840.10008.5.1.4.1.1.7.3",  # Multi-frame Grayscale Word SC
        "1.2.840.10008.5.1.4.1.1.7.4",  # Multi-frame True Color SC
    }
)

# Minimal 8-bit greyscale pixel data (2x2 pixels)
_MINIMAL_PIXEL_DATA = bytes([0x20, 0x40, 0x80, 0xC0])
# Minimal 8-bit RGB pixel data (2x2 pixels, 3 samples each)
_MINIMAL_RGB_DATA = bytes([0xFF, 0x00, 0x00] * 4)  # solid red 2x2


def _build_minimal_sc_dataset() -> Dataset:
    """Return a minimal well-formed SC dataset."""
    ds = Dataset()
    ds.SOPClassUID = "1.2.840.10008.5.1.4.1.1.7"
    ds.Modality = "OT"
    ds.ConversionType = "WSD"  # Workstation-derived
    ds.Rows = 2
    ds.Columns = 2
    ds.SamplesPerPixel = 1
    ds.PhotometricInterpretation = "MONOCHROME2"
    ds.BitsAllocated = 8
    ds.BitsStored = 8
    ds.HighBit = 7
    ds.PixelRepresentation = 0
    ds.PixelData = _MINIMAL_PIXEL_DATA
    return ds


class SecondaryCaptureFuzzer(FormatFuzzerBase):
    """Fuzzes DICOM Secondary Capture image objects.

    Targets SC parsers through pixel geometry violations, color space
    mismatches, frame-count buffer overflow attacks, and bit-depth
    inconsistencies.
    """

    def __init__(self) -> None:
        """Initialize SC fuzzer."""
        super().__init__()

    @property
    def strategy_name(self) -> str:
        """Return the strategy name for identification."""
        return "secondary_capture"

    def can_mutate(self, dataset: Dataset) -> bool:
        """Return True for SC datasets."""
        sop_class = str(getattr(dataset, "SOPClassUID", ""))
        if sop_class in _SC_SOP_CLASSES:
            return True
        # Accept SC by ConversionType (WSD, DF, CF, SD, etc.)
        conv_type = str(getattr(dataset, "ConversionType", ""))
        return conv_type in ("WSD", "DF", "CF", "SD", "WSD")

    def mutate(self, dataset: Dataset) -> Dataset:
        """Apply SC mutation.

        Args:
            dataset: DICOM dataset to mutate.

        Returns:
            Mutated dataset.

        """
        attacks = [
            self._color_space_mismatch,
            self._ycbcr_no_compression,
            self._frame_count_overflow,
            self._multiframe_no_timing,
            self._bits_allocated_64,
            self._bits_allocated_1_size_mismatch,
            self._no_pixel_data,
            self._empty_pixel_data,
            self._rgba_four_samples,
            self._rows_zero,
            self._conversion_type_missing,
            self._palette_color_missing_lut,
        ]

        attack = random.choice(attacks)
        try:
            attack(dataset)
            self.last_variant = attack.__name__.lstrip("_")
        except Exception:
            self.last_variant = "fallback"
            self._no_pixel_data(dataset)

        return dataset

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _ensure_sc_root(self, dataset: Dataset) -> None:
        """Ensure dataset has SC SOPClassUID and minimal attributes."""
        if not getattr(dataset, "SOPClassUID", None):
            dataset.SOPClassUID = "1.2.840.10008.5.1.4.1.1.7"
        if not hasattr(dataset, "Rows"):
            dataset.Rows = 2
            dataset.Columns = 2
        if not hasattr(dataset, "BitsAllocated"):
            dataset.BitsAllocated = 8
            dataset.BitsStored = 8
            dataset.HighBit = 7
        if not hasattr(dataset, "PixelData"):
            dataset.PixelData = _MINIMAL_PIXEL_DATA

    # ------------------------------------------------------------------
    # Attacks
    # ------------------------------------------------------------------

    def _color_space_mismatch(self, dataset: Dataset) -> None:
        """PhotometricInterpretation=RGB with SamplesPerPixel=1 (channel count mismatch)."""
        self._ensure_sc_root(dataset)
        dataset.PhotometricInterpretation = "RGB"
        dataset.SamplesPerPixel = (
            1  # RGB requires 3; parser allocates wrong buffer size
        )

    def _ycbcr_no_compression(self, dataset: Dataset) -> None:
        """YBR_FULL_422 declared but Transfer Syntax is uncompressed (decoder mismatch)."""
        self._ensure_sc_root(dataset)
        dataset.PhotometricInterpretation = "YBR_FULL_422"
        dataset.SamplesPerPixel = 3
        dataset.PixelData = _MINIMAL_RGB_DATA  # Raw bytes, not YBR-encoded

    def _frame_count_overflow(self, dataset: Dataset) -> None:
        """NumberOfFrames >> PixelData (OOB read in multi-frame SC iterator)."""
        self._ensure_sc_root(dataset)
        dataset.SOPClassUID = (
            "1.2.840.10008.5.1.4.1.1.7.2"  # Multi-frame Grayscale Byte SC
        )
        dataset.NumberOfFrames = 0xFFFF  # 65535 declared
        dataset.PixelData = _MINIMAL_PIXEL_DATA  # only 4 bytes

    def _multiframe_no_timing(self, dataset: Dataset) -> None:
        """NumberOfFrames=10 with no FrameTime or FrameTimeVector (timing div-by-zero)."""
        self._ensure_sc_root(dataset)
        dataset.SOPClassUID = "1.2.840.10008.5.1.4.1.1.7.2"
        dataset.NumberOfFrames = 10
        dataset.PixelData = _MINIMAL_PIXEL_DATA * 10
        # Deliberately omit FrameTime, FrameTimeVector, FrameIncrementPointer
        for attr in ("FrameTime", "FrameTimeVector", "FrameIncrementPointer"):
            if hasattr(dataset, attr):
                delattr(dataset, attr)

    def _bits_allocated_64(self, dataset: Dataset) -> None:
        """BitsAllocated=64 (non-standard -- parser dispatch confusion for float pixels)."""
        self._ensure_sc_root(dataset)
        dataset.BitsAllocated = 64
        dataset.BitsStored = 64
        dataset.HighBit = 63
        # Only 4 bytes of pixel data -- far less than 64-bit depth requires
        dataset.PixelData = _MINIMAL_PIXEL_DATA

    def _bits_allocated_1_size_mismatch(self, dataset: Dataset) -> None:
        """BitsAllocated=1 with byte-aligned pixel data (bitonal packing logic crash)."""
        self._ensure_sc_root(dataset)
        dataset.SOPClassUID = "1.2.840.10008.5.1.4.1.1.7.1"  # Multi-frame Single Bit SC
        dataset.BitsAllocated = 1
        dataset.BitsStored = 1
        dataset.HighBit = 0
        dataset.Rows = 8
        dataset.Columns = 8
        dataset.NumberOfFrames = 1
        # Should be ceil(8*8/8)=8 bytes; give 100 to trigger over-read
        dataset.PixelData = bytes(100)

    def _no_pixel_data(self, dataset: Dataset) -> None:
        """SC SOPClassUID + large clinical dimensions but no PixelData."""
        dataset.SOPClassUID = "1.2.840.10008.5.1.4.1.1.7"
        dataset.Modality = "OT"
        dataset.ConversionType = "WSD"
        dataset.Rows = 1920
        dataset.Columns = 1080
        dataset.SamplesPerPixel = 3
        dataset.PhotometricInterpretation = "RGB"
        dataset.BitsAllocated = 8
        if hasattr(dataset, "PixelData"):
            del dataset.PixelData

    def _empty_pixel_data(self, dataset: Dataset) -> None:
        """PixelData present but zero bytes (empty buffer with non-zero declared geometry)."""
        self._ensure_sc_root(dataset)
        dataset.Rows = 512
        dataset.Columns = 512
        dataset.PixelData = b""  # zero bytes despite 512x512 declared

    def _rgba_four_samples(self, dataset: Dataset) -> None:
        """SamplesPerPixel=4 with RGB photometric (RGBA / alpha channel not in DICOM)."""
        self._ensure_sc_root(dataset)
        dataset.PhotometricInterpretation = "RGB"
        dataset.SamplesPerPixel = 4  # ARGB -- not standard in DICOM

    def _rows_zero(self, dataset: Dataset) -> None:
        """Rows=0 / Columns=0 (divide-by-zero in dimension-based buffer allocation)."""
        self._ensure_sc_root(dataset)
        dataset.Rows = 0
        dataset.Columns = 0
        dataset.PixelData = _MINIMAL_PIXEL_DATA  # data present despite zero dims

    def _conversion_type_missing(self, dataset: Dataset) -> None:
        """Multi-frame SC without ConversionType (required Type 1 attribute absent)."""
        self._ensure_sc_root(dataset)
        dataset.SOPClassUID = "1.2.840.10008.5.1.4.1.1.7.2"
        dataset.NumberOfFrames = 5
        dataset.PixelData = _MINIMAL_PIXEL_DATA * 5
        if hasattr(dataset, "ConversionType"):
            del dataset.ConversionType

    def _palette_color_missing_lut(self, dataset: Dataset) -> None:
        """PALETTE COLOR declared but Red/Green/BluePaletteColorLookupTableData absent."""
        self._ensure_sc_root(dataset)
        dataset.PhotometricInterpretation = "PALETTE COLOR"
        dataset.SamplesPerPixel = 1
        dataset.BitsAllocated = 8
        dataset.PixelData = _MINIMAL_PIXEL_DATA
        # Deliberately omit all LUT Data attributes:
        #   RedPaletteColorLookupTableDescriptor, etc.
        for attr in (
            "RedPaletteColorLookupTableData",
            "GreenPaletteColorLookupTableData",
            "BluePaletteColorLookupTableData",
        ):
            if hasattr(dataset, attr):
                delattr(dataset, attr)
