name: Stale Issue and PR Management

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Mark Stale Issues and PRs
    runs-on: ubuntu-latest
    steps:
      - name: Stale Management
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Issue settings
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed in 7 days if no further activity occurs.

            If this issue is still relevant, please add a comment to keep it open.
            Thank you for your contributions! 🙏
          close-issue-message: |
            This issue was automatically closed due to inactivity.
            If you believe this issue is still relevant, please reopen it or create a new issue.
            Thank you! 🙏
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug'

          # PR settings
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed in 14 days if no further activity occurs.

            Please update this PR or let us know if you're still working on it.
            Thank you for your contribution! 🙏
          close-pr-message: |
            This pull request was automatically closed due to inactivity.
            If you'd like to continue this work, please reopen the PR or create a new one.
            Thank you! 🙏
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,work-in-progress'

          # General settings
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: true
